### ISSUE TITLE
Improper holes and bumps in the generated surface using Lerc.dll

### ISSUE THREAD

**Issue by TerraUnity** [Esri/lerc#138] opened 2020-08-24 06:25 UTC
Latest Windows decoder "Lerc.dll" has some artifacts when generating heights data for the surface. It generates unwanted holes and bumps while decoding some tiles as shown in the following pictures.

![Holes](https://user-images.githubusercontent.com/27004936/91010646-1bd7d080-e5f8-11ea-80d3-10214d226128.JPG)

![Holes2](https://user-images.githubusercontent.com/27004936/91010655-1f6b5780-e5f8-11ea-9929-c302b0282c7f.JPG)

Did not test on Mac & Linux yet but it could be the same for these libraries too.

**Comment by tmaurer3** [comment] 2020-08-24 17:15
@TerraUnity  It depends. Can you share more details - how the data got Lerc encoded, using which z tolerance. Looks like you are zooming in pretty close. May not be a bug, just the artifacts from lossy encoding. Like zooming into a jpeg image at pixel level and making jpeg artifacts visible. In case you encoded the Lerc tiles yourself, repeat again and set z tolerance to 0 (lossless). Then there should be no such artifacts.

**Comment by TerraUnity** [comment] 2020-08-25 06:05
I can confirm that decoding is lossless and heights data comes straight from the 2D array of floats and no raster compression is involved. Also this happens only on some specific tiles and the rest are fine!

Following are shots both with the old dll we used and yields proper result versus the latest dll here on GitHub with artifacts, both with exact same default settings.

Latest DLL
![LercDecoder_Latest](https://user-images.githubusercontent.com/27004936/91128550-a59da180-e6bd-11ea-953f-e06847e8e3d0.JPG)
Old DLL
![LercDecoder_Old](https://user-images.githubusercontent.com/27004936/91128558-a8989200-e6bd-11ea-8a82-4e39ec9370ef.JPG)

Latest DLL
![LercDecoder_Latest_Close](https://user-images.githubusercontent.com/27004936/91128566-ac2c1900-e6bd-11ea-92a0-0f513a854f1a.JPG)
Old DLL
![LercDecoder_Old_Close](https://user-images.githubusercontent.com/27004936/91128571-ae8e7300-e6bd-11ea-9b9e-d358af26beb7.JPG)
_(Ignore the steps on surface as these are due to further resampling of the data)_

FYI, we have been using Lerc Decoder since a year ago in our Unity engine extension and this issue existed since we have updated the dlls to the latest one here. Also I have prepared the Mac version of the dll decoder here in this repo.

**Comment by tmaurer3** [comment] 2020-08-25 17:14
@TerraUnity  In that case, can you give me one such sample tile (as an array of float, raw binary, 4 bytes per float, with width and height of that tile). Or as a small tiff image. I assume all pixels are valid, so there is no mask. Then your encode and decode calls with parameters. So I can analyze it.

**Comment by tmaurer3** [comment] 2020-12-28 19:15
@TerraUnity  No one else has reported this or similar issue. I'm closing this as not reproducible. If you run into this again, please reopen this issue with a repro sample.

**Closed by tmaurer3** 2020-12-28 19:15 UTC
